config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#show"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :photos, only: [:index, :create, :show, :update, :destroy]
    end
  end

  resources :subject_tags

  resources :users do

    member do
      get :viewfile
    end

    resources :plans do
      resources :teachingfiles do
        resources :attachments, only: :destroy do
        end
      end
    end

    resources :materials do
      resources :teachingfiles do
        resources :attachments, only: :destroy do
        end
      end
    end

    resources :classrooms do
      resources :topics do
        resources :teachingfiles do
          member do
            post :addfile
            post :removefile
          end
        end
        
        resources :aims
      end
    end

    resources :subjects

    resources :events

    resources :lessons do
      collection do
        get :list
      end
    end
  end

end

app/models/topic.rb
#  == Schema Information
#
#  Table names : topics
#
#  id                :integer     not null, primary key
#  name              :string
#  set_week          :datetime
#  aim               :string
#  accessment        :integer
#  file_upload       :string
#  feedback_title    :string
#  feedback_content  :text
#  created_at        :datetime    not null
#  updated_at        :datetime    not null
#
#  subject_id        :integer

class Topic < ApplicationRecord
  belongs_to :subject, optional: true

  ###lesson不再直接屬於topic , 所以這行要刪掉，不然會出現ActiveRecord::StatementInvalid (SQLite3::SQLException: no such column: lessons.topic_id: SELECT "lessons".* FROM "lessons" WHERE "lessons"."topic_id" = ?)
  #has_many :lessons, dependent: :destroy

  belongs_to :classroom,optional: true

  has_many :addfiles, dependent: :destroy 
  # topic 刪掉， addfile 上也不會有檔案，但 teachingfiles上的應保留
  has_many :added_files, through: :addfiles, source: :teachingfile

  has_many :aims,dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_user, only: [:show, :create, :update, :destroy]
  before_action :set_classroom, only: [:show, :create, :update, :destroy]
  before_action :set_topic, only: [:show, :update, :destroy]

  def show
    @subjects = @user.subjects
    @materials = @user.materials
    @plans = @user.plans
    @addfiles = @topic.addfiles.all
  end  
 
  def create
    @topic = @classroom.topics.create(topic_params)

    #respond_to do |format|
      if @topic.save
        #format.html{redirect_to user_classroom_url(@user,@classroom),notice:"成功新增教學主題" }
        #format.json{render :show, status: :created, location: @topic}
        #format.js
        flash[:notice]= "成功新增教學主題"
        redirect_back fallback_location: root_path
      else
        #format.html{redirect_to user_classroom_url(@user,@classroom),alert:"新增失敗，請完全填妥教學計劃表格資訊"}
        #format.json{render json: @topic.errors,status: :unprocessable_entity}
        #format.js
        flash[:alert]= "新增失敗，請完全填妥教學計劃表格資訊"
        redirect_back fallback_location: root_path
      end
    #end 
  end 

  def update
    #respond_to do |format|
      if @topic.update(topic_params)
        #format.html{redirect_to user_subject_url(@user,@subject),notice:"成功更新教學計劃" }
        #format.json{render :show, status: :ok, location: @topic}  
        #format.js 
        flash[:notice]= "成功更新教學主題"
        redirect_back fallback_location: root_path
      else
        #format.html{redirect_to user_subject_url(@user,@subject),alert:"更新失敗，請完全填妥教學計劃表格資訊"}
        #format.json{render json: @topic.errors,status: :unprocessable_entity} 
        #format.js
        flash[:alert]= "新增失敗，請完全填妥教學計劃表格資訊"
        redirect_back fallback_location: root_path
      end
    #end
  end

  def destroy
    @topic.destroy
    #respond_to do |format|
      #format.html{redirect_to user_subject_url(@user,@subject),notice:"成功刪除一個教學計劃" }
      #format.json{head :no_content}  
      #format.js
    #end
    flash[:notice]= "成功刪除一個教學單元"
    redirect_back fallback_location: root_path
  end


  private
  def set_user
    @user = current_user
  end

  def set_classroom
    @classroom = @user.classrooms.find(params[:classroom_id])
  end

  def set_topic
    @topic = @classroom.topics.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:name,:subject_id,:classroom_id,:start_time,:end_time,:feedback)
  end
end

app/views/topics/_materials.html.erb
<div class="col margin-right-10">
  <h2>教材檔案</h2>
  <br>

  <% if @materials.count == 0 %>
    <p class="font-22">尚未上傳任何<strong>教材</strong>檔案</p>
    <%= link_to "新增教材檔案", user_materials_path(@user), class: "font-24" %>
  <% else %>
    <% @subject_tags.each do |subject| %>
      <% if SubjectTag.where(name: subject.name).first.materials.where(user_id: @user).present? %>
        <h3><strong><%= subject.name %></strong></h3>

        <% @materials.each do |material| %>
          <% if material.subject_tag.name == subject.name %>
            <div class="table-card radius-20 margin-bottom-30">
              <h4><%= material.mtrial_folder_name %></h4>
              <hr>

              <div class="col">
                <% material.teachingfiles.each do |teachingfile| %>
                  <h5>
                    <%= fa_icon 'folder' %>
                    <%= teachingfile.name %>
                    <div class="float-right">
                      <% if teachingfile.is_added?(@topic) %>
                        <%= link_to removefile_user_classroom_topic_teachingfile_path(@user,@classroom,@topic,teachingfile), method: :post, remote: true do %>
                          <%= fa_icon 'minus 2x', style: 'color: #6c757d;' %>
                        <% end %>
                      <% else %>
                        <%= link_to addfile_user_classroom_topic_teachingfile_path(@user,@classroom,@topic,teachingfile), method: :post, remote: true do %>
                          <%= fa_icon 'plus 2x', style: 'color: #6c757d;' %>
                        <% end %>
                      <% end %>
                    </div>
                  </h5>
                  <% teachingfile.attachments.each do |file| %>
                    <li><i><%= file.file.filename %></i></li>
                  <% end %>
                  <br>
                <% end %>
              </div>

            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/topics/_plans.html.erb
<div class="col" style="border-left: 1px solid #d9dedd;">
  <h2>教案檔案</h2>
  <br>

  <% if @plans.count == 0 %>
    <p class="font-22">尚未上傳任何<strong>教材</strong>檔案</p>
    <%= link_to "新增教材檔案", user_plans_path(@user), class: "font-24" %>
  <% else %>
    <% @subject_tags.each do |subject| %>
      <% if SubjectTag.where(name: subject.name).first.plans.where(user_id: @user).present? %>
        <h3><strong><%= subject.name %></strong></h3>

        <% @plans.each do |plan| %>
          <% if plan.subject_tag.name == subject.name %>
            <div class="table-card radius-20 margin-bottom-30">
              <h4><%= plan.plan_folder_name %></h4>
              <hr>

              <div class="col">
                <% plan.teachingfiles.each do |teachingfile| %>
                  <h5>
                    <%= fa_icon 'folder' %>
                    <%= teachingfile.name %>

                    <div class="float-right">
                      <% if teachingfile.is_added?(@topic) %>
                        <%= link_to removefile_user_classroom_topic_teachingfile_path(@user,@classroom,@topic,teachingfile), method: :post, remote: true do %>
                          <%= fa_icon 'minus 2x', style: 'color: #6c757d;' %>
                        <% end %>
                      <% else %>
                        <%= link_to addfile_user_classroom_topic_teachingfile_path(@user,@classroom,@topic,teachingfile), method: :post, remote: true do %>
                          <%= fa_icon 'plus 2x', style: 'color: #6c757d;' %>
                        <% end %>
                      <% end %>
                    </div>
                  </h5>
                  <% teachingfile.attachments.each do |file| %>
                    <li><i><%= file.file.filename %></i></li>
                  <% end %>
                  <br>
                <% end %>
              </div>

            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/topics/_topic.html.erb
<div id="post_<%= topic.id %>">
  
  <!--<div class="col-md-12">-->
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-9 weekly-prepare">
        
          <!--教學單元主題-->
        <div class="topic-title">
          <h3 class="float-left"><%= topic.name %></h3>
          <h3 class="float-right">
            <% if @user == current_user %>
              <%= topic.start_time.strftime("%Y/%m/%d") %> - <%= topic.end_time.strftime("%Y/%m/%d") %>&nbsp;
            
              <button class="round-button" alt="重設日期／主題" type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatepost_<%= topic.id  %>"><%= fa_icon 'calendar', style: 'cursor: pointer;'%></button>
            <% else %>
              <%= topic.start_time.strftime("%Y/%m/%d") %> - <%= topic.end_time.strftime("%Y/%m/%d") %>
            <% end %>
          </h3>
          <div class="clearfix"></div>
        </div>

        <div class="container">
          <div class="row">
            <div class="col-10 prepare-detail">
              <!--教學單元主題下的教學目標-->
              <% if @user == current_user %>
                <%= form_for [@user,@classroom,topic,Aim.new],remote: true do |f| %>
                  <h4><%= f.label :title, "教學目標" %></h4>
                  <div class="form-group form-inline"> 
                    <%= f.text_field :name, placeholder:"新增教學目標", class: "form-control new-aim" %>
                    <%= f.submit "新增", class: "btn btn-outline-info" %>
                  </div>
                <% end %>
              
                <ol id="aim_posts-<%= topic.id %>">
                  <% topic.aims.each do |aim| %> 
                    <%= render :partial => 'aims/aim', locals: {aim: aim } %>               
                  <% end %> 
                </ol> 
              <% else %>
                <h4>教學目標</h4>
              
                <ol id="aim_posts-<%= topic.id %>">
                  <% topic.aims.each do |aim| %> 
                    <%= render :partial => 'aims/aim', locals: {aim: aim } %>               
                  <% end %> 
                </ol> 
              <% end %>        
            </div>
            <div class="col-2">
              <div class="prepare-edit">
                <% if @user == current_user %>
                  <%= link_to user_classroom_topic_path(@user, @classroom, topic) do %>
                    <div class="prepare-edit-div" data-toggle="tooltip" data-placement="left" title="取得教材／教案檔案"><%= fa_icon 'plus-square-o', style: 'font-size: 25px;' %></div>
                  <% end %> 

                  <div class="prepare-edit-div" data-toggle="tooltip" data-placement="left" title="查看現有教學檔案">
                    <div data-toggle="modal" data-target="#bd-example-modal-lg-<%= topic.id %>">
                      <%= fa_icon 'folder', style: 'font-size: 25px; cursor: pointer;' %>
                    </div>
                  </div>
                  <div class="prepare-edit-div" data-toggle="tooltip" data-placement="left" title="填寫教學反思">
                    <div data-toggle="modal" data-target="#myupdatefeedback_<%= topic.id  %>">
                      <%= fa_icon 'edit', style: 'font-size: 25px; cursor: pointer;' %>
                    </div>
                  </div>
                <% else %>
                  <div class="prepare-edit-div" data-toggle="tooltip" data-placement="left" title="查看現有教學檔案">
                    <div data-toggle="modal" data-target="#bd-example-modal-lg-<%= topic.id %>">
                      <%= fa_icon 'folder', style: 'font-size: 25px; cursor: pointer;' %>
                    </div>
                  </div>
                <% end %>

              </div>
              
              <% if @user == current_user %>
                <div class="parent-absolute">
                  <div class="prepare-edit-div3" data-toggle="tooltip" data-placement="left" title="刪除教學計劃">
                    <%= link_to user_classroom_topic_path(@user,@classroom,topic) ,method: :delete, data: { confirm: "確定要刪除此教學單元嗎?"}, remote: true do %>
                      <%= fa_icon 'trash', style: 'font-size: 25px;' %>
                    <% end %>
                      
                  </div>
                </div>
              <% end %>

            </div>
        </div>

      </div>
    </div>
  </div>
  
  <!-- FILE DOWNDOAD MODAL-->
  <div class="modal fade" id="bd-example-modal-lg-<%= topic.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">
            下載教學檔案
          </h5>
          
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if topic.added_files.count == 0 %>
            <h5>本計劃尚未放進任何教案／教材檔案，可點選計劃表上的 <%= fa_icon 'plus-square-o' %> 取得檔案 </h5>
          <% else %>
            <div class="row">
              <div class="col-md-4 float-left">
                <% topic.added_files.each do |teachingfile| %>
                  <div style="text-align: left; margin-left: 20px;">
                    <h5>
                      <%= fa_icon 'folder' %>
                      <%= teachingfile.name %>
                        
                    </h5>
                    <% teachingfile.attachments.each_with_index do |file, index| %>
                      <li>
                        <%= link_to file.url do %>
                          <%= fa_icon 'download', class: 'theme-font'%>&nbsp;&nbsp;
                          <span style="color: blue;"><%= file.file.filename %></span>
                        <% end %>
                      </li>
                    <% end %>                    
                  </div>
                  <br>
                <% end %>
              </div>
            </div>
          <% end %>  
        </div>       
      </div>
    </div>
  </div>
</div>


<!--modal - update topic posts-->
<%= form_for [@user,@classroom,topic] ,method: :put,remote: true  do |f| %>
  <div class="modal fade" id="myupdatepost_<%= topic.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="myModalLabel">編輯教學主題</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
              <!--輸入主題日期開始-->
              <div class="field">
                <%= f.label "開始日期" %>
                <%= f.date_select :start_time, class: 'form-control post_theme', placeholder: "ex: 2018/9/14" %>
              </div>

              <!--輸入主題日期結束-->
              <div class="field">
                <%= f.label "結束日期" %>
                <%= f.date_select :end_time, class: 'form-control post_theme', placeholder: "ex:2018/9/21" %>
              </div>

              <!--輸入教學主題-->
              <div class="field">
                <%= f.label "教學單元主題" %>
                <%= f.text_field :name, class: 'form-control', placeholder: "輸入教學主題" %>
              </div>

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="mypostclose">close</button>
            <%= submit_tag "Update",class:"btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
<% end %> 
<!--update modal-->


<!--modal - update feedback posts -->
<%= form_for [@user,@classroom,topic] ,method: :put,remote: true  do |f| %>
  <div class="modal fade" id="myupdatefeedback_<%= topic.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-md modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="myModalLabel">教學反思與紀錄</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">

            <div class="field">
              <%= f.label "教學反思與紀錄" %>
              <%= f.trix_editor :feedback, placeholder: "輸入教學後的心得＆反思" %>
            </div>


          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="mypostclose">close</button>
            <%= submit_tag "Update",class:"btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
<% end %>
<!--update modal-->

<script>
  $('trix-editor').css("min-height", "350px");
</script>

app/views/topics/destroy.js.erb
$("#post_<%= @topic.id %> ").fadeOut(500,function(){
  $(this).remove();
  

});

app/views/topics/show.html.erb
<div class="container">
  <div id="topic-show-top">
    <span class="h1-font">上傳檔案總覽</span>
    <span class="right-link">
      <%= link_to 'javascript:history.back()' do %>
        <p class="font-20">返回班級教學計劃&nbsp;
          <%= fa_icon 'caret-right' %>
        </p>
      <% end %>

    </span>
  </div>

  <hr>
  <div class="row">
    <%= render partial: "materials" %>
    <%= render partial: "plans" %>
  </div>
  <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
  <!--這裡可以用上 kaminari 分頁 -->
</div>

<script>
  window.onscroll = function() {scrollFunction()};

  function scrollFunction() {
      if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
          document.getElementById("myBtn").style.display = "block";
      } else {
          document.getElementById("myBtn").style.display = "none";
      }
  }

  // When the user clicks on the button, scroll to the top of the document
  function topFunction() {
      document.body.scrollTop = 0; // For Safari
      document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
  }
</script>

app/views/topics/update.js.erb
$("#myupdatepost_<%= @topic.id %>").modal('hide');
$("#myupdatefeedback_<%= @topic.id %>").modal('hide');

<% html = j( render :partial => "topics/topic", :locals => { :topic => @topic } ) %>
$("#post_<%= @topic.id %>").fadeOut(500,function(){
  $(this).replaceWith("<%= render @topic %>");
});