config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#show"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :photos, only: [:index, :create, :show, :update, :destroy]
    end
  end

  resources :subject_tags

  resources :users do

    member do
      get :viewfile
    end

    resources :plans do
      resources :teachingfiles do
        resources :attachments, only: :destroy do
        end
      end
    end

    resources :materials do
      resources :teachingfiles do
        resources :attachments, only: :destroy do
        end
      end
    end

    resources :classrooms do
      resources :topics do
        resources :teachingfiles do
          member do
            post :addfile
            post :removefile
          end
        end
        
        resources :aims
      end
    end

    resources :subjects

    resources :events

    resources :lessons do
      collection do
        get :list
      end
    end
  end

end

app/views/shared/_alert.html.erb
  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible" role="alert"><%= notice %>
      <button class="close" type="button" data-dismiss="alert" aria-lable="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger alert-dismissible" role="alert"><%= alert %>
      <button class="close" type="button" data-dismiss="alert" aria-lable="alert">
      <span aria-hidden="true">&times;</span>
    </button>
    </div>
  <% end %>

app/views/shared/_materialform.html.erb
<style>
  .field{
    width: 65%;
    margin: 10px auto;
  }

  .field.field-category{
    margin-bottom: -15px;
  }
</style>

<% if @material.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @material.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %> 

<%= form_for [@material] do |f| %>
  <div class="field field-category">
  <%= f.label :topic_id, "科目" %><br>
  <%= f.collection_select :topic_id , Topic.all, :id, :name, {prompt: true}, {class: "form-control"}  %><br>
  </div> 

  <div class="field">
  <%= f.label :title, "教材資料夾名稱" %><br>
  <%= f.text_field :title ,class:"form-control"%>
  </div>

  <div class="field">
    <%= f.submit%><br>
  </div>
    
<div class="field">
  <%= link_to 'Index Page',root_path,class:"btn btn-primary form-control" %>
</div>

<% end %>

app/views/shared/_msg.html.erb
<% if @lesson.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @lesson.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.svg", width:'45', height:'45', alt:'首頁', class: "d-inline-block",style:"margin-left:18px;" %>
     <strong class="font-20 letter-sp-2" style="margin-left: 15px;">K12 Project</strong>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user %>
      <ul class="nav">
        <li style="border-left: 2px solid #ebebeb; padding-top: 4px;"><%= link_to '課表首頁', user_lessons_path(@user) %></li>

        <li class="dropdown" style="position:relative; border-left: 2px solid #ebebeb;; padding-top: 4px;">
          <a href="#" class=" dropdown-toggle" data-toggle="dropdown">我的班級<span class="caret"></span></a>
          <%# 設定第一層：科目 %>
          <ul class="dropdown-menu">
            <% if @subjects.count == 0 %>
              <li><%= link_to '請先新增課表', new_user_lesson_path(@user) %></li>
            <% else %>
              <% @subjects.each do |subject| %>
              
                <li>     
                  <a class="trigger right-caret"><%= subject.name if subject.classrooms.exists? %></a>
                  <%# 設定第二層：科目下的班級 %>
                  <ul class="dropdown-menu sub-menu">
                  
                    <% subject.classrooms.each do |classroom| %>
                      <li>
                        <%= link_to user_classroom_path(@user,classroom) do %>
                          <%= classroom.name %>
                        <% end %>
                      </li>  
                    <% end %>
                    
                  </ul>
                </li>
              <% end %>
            <% end %>
            
            
          </ul>
        </li>
        
        <li style="border-left: 2px solid #ebebeb; padding-top: 4px;"><%= link_to '教材資料夾', user_materials_path(@user) %></li>
        <li style="border-left: 2px solid #ebebeb; padding-top: 4px;"><%= link_to '教案資料夾', user_plans_path(@user) %></li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="font-size: 20px;letter-spacing: 1px;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar? %>
              <%= image_tag current_user.avatar, width: '30', height: '30' %>
            <% else %>
              <%= image_tag 'avatar-default.png', width: '30', height: '30' %>  
            <% end %>
            <%= current_user.name %>
            
          </a>
          <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="navbarDropdown">
            <%= link_to('個人檔案', edit_user_path(current_user), class: 'dropdown-item theme-font') %>  
            <div class="dropdown-divider"></div>
            <%= link_to('登出', destroy_user_session_path, method: :delete, class: "dropdown-item theme-font") %>
          </div>
          
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav navbar-right">
        <li class='navbar-nav-li'><%= link_to('Sign up', new_user_registration_path) %> or <%= link_to('Log in', new_user_session_path) %></li>
        <li></li>
      </ul>
    <% end %>
  <% end %>

</nav>

<script>
  $(function(){
    $(".dropdown-menu > li > a.trigger").on("click",function(e){
        var current=$(this).next();
        var grandparent=$(this).parent().parent();
        if($(this).hasClass('left-caret')||$(this).hasClass('right-caret'))
            $(this).toggleClass('right-caret left-caret');
        grandparent.find('.left-caret').not(this).toggleClass('right-caret left-caret');
        grandparent.find(".sub-menu:visible").not(current).hide();
        current.toggle();
        e.stopPropagation();
    });
    $(".dropdown-menu > li > a:not(.trigger)").on("click",function(){
        var root=$(this).closest('.dropdown');
        root.find('.left-caret').toggleClass('right-caret left-caret');
        root.find('.sub-menu:visible').hide();
    });
});
</script>

app/views/shared/_planform.html.erb
<style>
  .field{
    width: 65%;
    margin: 10px auto;
  }

  .field.field-category{
    margin-bottom: -15px;
  }
</style>

<% if @plan.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @plan.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %> 

<%= form_for [@plan] do |f| %>
  <div class="field field-category">
  <%= f.label :topic_id, "科目" %><br>
  <%= f.collection_select :topic_id , Topic.all, :id, :name, {prompt: true}, {class: "form-control"}  %><br>
  </div> 

  <div class="field">
  <%= f.label :title, "教案資料夾名稱" %><br>
  <%= f.text_field :title ,class:"form-control"%>
  </div>

  <div class="field">
    <%= f.submit%><br>
  </div>
    
<div class="field">
  <%= link_to 'Index Page',root_path,class:"btn btn-primary form-control" %>
</div>

<% end %>

app/views/shared/_sidebar.html.erb
<% if signed_in? %>
  <div class="sidenav">
    <div class="dropdown-btn text-center">
      <% if current_user.avatar? %>
        <%= link_to user_path(@user) do %>
          <%= image_tag current_user.avatar,class: "img-fluid"%>
          <h4 class="text-center"><%= @user.name %></h4>
        <% end %>
      <% else %>
        <%= image_tag 'avatar-default.png', class: 'img-fluid' %>
        <h4 class="text-center"><%= @user.name %></h4>
      <% end %>
      
    </div>

    <hr>

    <div class="dropdown-container">
      <h5 style="color:green">
        你還沒有任何教學計劃哦！先新增班級吧！
      </h5>  
    </div>

    <button class="dropdown-btn">
      <%= '我的班級' %>
      <%= fa_icon 'caret-down' %>
    </button>
    <div class="dropdown-container">
      <%#= link_to " + 新建班級", new_user_subject_path(@user, @subject) %>
      <%= link_to user_lessons_path(@user) do %>
        <%= fa_icon 'home' %> <%= '課表首頁' %>
      <% end %>
      <%= link_to user_subjects_path(@user) do %>
        <%= fa_icon 'desktop' %> <%= "班級管理" %>
      <% end %>
      <button class="dropdown-btn">
        <%= " - 現有班級" %>
        <%= fa_icon 'caret-down' %>  
      </button>
      <% if @subjects.count == 0 %>
        <div class="dropdown-container">        
          <h5 style="color:green;">你還沒有任何班級哦！趕緊新建一個吧！</h5>
        </div>
      <% else %>
        <div class="dropdown-container">
          <% @subjects.each do |subject| %>
            <%= link_to user_subject_path(@user, subject) do %>
              <%= subject.classroom %>
            <% end %>
          <% end %>
        </div>        
      <% end %>
    </div>    
      

    <!--第一個dropdown-->
    <button class="dropdown-btn">
      <%= '我的教材' %>
      <%= fa_icon 'caret-down' %>
    </button>
    <div class=dropdown-container>
      <%= link_to " + 新增教材資料夾" ,new_user_material_path(@user, @material)  %>
      <!--第二層 dropdown開始-->
      <button class="dropdown-btn">
        <%= " - 現有教材" %>
        <%= fa_icon 'caret-down' %>
      </button>
      <% if @materials.count == 0 %>
        <div class="dropdown-container">
          <h5 style="color:green;">尚未建立任何資料夾</h5>
        </div>
      <% else %>
        <div class="dropdown-container">
          <% @subject_tags.each do |subject| %>

            <% if subject.materials.present? %>
            <button class="dropdown-btn">
              <%= "【" + subject.name + "】" %>
              <%= fa_icon 'caret-down' %>
            </button>
            <div class="dropdown-container">
              <% subject.materials.each do |material| %>
                <%= link_to material.mtrial_folder_name, user_material_path(@user, material) %>
              <% end %>
            </div>
            <% end %>

          <% end %>
        </div>
      <% end %>
    </div>

    <button class="dropdown-btn">
      <%= '我的教案' %>
      <%= fa_icon 'caret-down' %>
    </button>
    <div class=dropdown-container>
      <%= link_to " + 新增教案資料夾", new_user_plan_path(@user, @plan) %>
      <button class="dropdown-btn">
        <%= " - 現有教案" %>
        <%= fa_icon 'caret-down' %>
      </button>
      <% if @plans.count == 0 %>
        <div class="dropdown-container">
          <h5 style="color:green;">尚未建立任何資料夾</h5>
        </div>
      <% else %>
        <div class="dropdown-container">
          <% @subject_tags.each do |subject| %>

            <% if subject.plans.present? %>
            <button class="dropdown-btn">
              <%= "【" + subject.name + "】" %>
              <%= fa_icon 'caret-down' %>
            </button>
            <div class="dropdown-container">
              <% subject.plans.each do |plan| %>
                <%= link_to plan.plan_folder_name, user_plan_path(@user, plan) %>
              <% end %>
            </div>
            <% end %>

          <% end %>
        </div>
      <% end %>
    </div>
       
  </div>
<% end %>