config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#show"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :photos, only: [:index, :create, :show, :update, :destroy]
    end
  end

  resources :subject_tags

  resources :users do

    member do
      get :viewfile
    end

    resources :plans do
      resources :teachingfiles do
        resources :attachments, only: :destroy do
        end
      end
    end

    resources :materials do
      resources :teachingfiles do
        resources :attachments, only: :destroy do
        end
      end
    end

    resources :classrooms do
      resources :topics do
        resources :teachingfiles do
          member do
            post :addfile
            post :removefile
          end
        end
        
        resources :aims
      end
    end

    resources :subjects

    resources :events

    resources :lessons do
      collection do
        get :list
      end
    end
  end

end

app/models/lesson.rb
#  == Schema Information
#
#  Table names : lessons
#
#  id            :integer     not null, primary key
#  name          :string
#  start_time    :datetime
#  end_time      :datetime
#  created_at    :datetime    not null
#  updated_at    :datetime    not null
#
#  topic_id      :integer 

class Lesson < ApplicationRecord
  attr_accessor :period, :frequency, :commit_button
  validates_presence_of :name

  belongs_to :classroom, optional: true

  REPEATS = ["整個學期"]

  def lesson?
    self.event_type == "lesson"
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  # before_action :set_subject_of_lesson, only: [:edit]

  before_action :set_subject_of_lesson, only: [:show]

  before_action :set_user, only: [:index, :show, :list]
  before_action :set_lessons, only: [:index, :list]

  before_action :authenticate_user!# index 改設定為 root，巢狀內的 root 必需加的設定
  before_action :authenticate_author, except: [:index, :show, :list]
  before_action :set_author, only: [:new, :create, :edit, :update, :destroy]

  def index
    # _to_do_list
    # 預設日期，重新整理回到今天
    @day = Date.today

    # 隱私問題，使用者只能看到自己的待辦事項
    @todos = current_user.events.all
    @todo = current_user.events.new
  end
 
  def show
    @lesson = Lesson.find(params[:id])
    # HABTM 關聯方法        
    @topic = Topic.new
    @topics = @classroom.topics.order(created_at: :desc)

    if params[:classroom_id] 
      @topic = @classroom.topics.find(params[:topic_id])
      @aim = @topic.aims.find(params[:id])     
    end

    @added_files = @topic.added_files

  end

  def list
  end

  # 新增一堂課，預設 end_time 現在時間一小時後，period "Does not repeat"
  def new
    # debug：先 create 就多出無用的資料了，用 new
    subject = @user.subjects.new
    classroom = Classroom.new
    @lesson = classroom.lessons.new
    # render :json => {:form => render_to_string(:partial => 'form')}
  end
  
  # 此處 period 是 :commit 參數，不是 lesson table 的欄位
  def create
    #if params[:lesson][:period] == "單一節次"

      # 時間在資料庫的時區是 +0
      #@classroom = @user.classrooms.find_or_initialize_by(name: (params[:lesson][:grade] + params[:lesson][:room]), grade: params[:lesson][:grade], room: params[:lesson][:room], student: params[:lesson][:student])

      #@lesson = @classroom.lessons.new(lesson_params)
      #@lesson.end_time = @lesson.start_time + 1.hour

    #else # params[:lesson][:period] == "整個學期"

      #直接預設新增就是整個學期
      @classroom = @user.classrooms.find_or_initialize_by(name: (params[:lesson][:grade] + params[:lesson][:room]), grade: params[:lesson][:grade], room: params[:lesson][:room], student: params[:lesson][:student])

      start = Time.new(params[:lesson]['start_time(1i)'],params[:lesson]['start_time(2i)'],params[:lesson]['start_time(3i)'],params[:lesson]['start_time(4i)'],params[:lesson]['start_time(5i)'])

      # 判斷 break point
      date_year = params[:lesson]['start_time(1i)'].to_i
      date_month = params[:lesson]['start_time(2i)'].to_i
      if date_month.between?(7,12)
        semester = Time.new(date_year,7,1)..Time.new(date_year + 1,1,31).end_of_day # 沒加 end_of_day 最後一天的事件會漏掉
      elsif  date_month.between?(1,1)
        semester = Time.new(date_year - 1,7,1)..Time.new(date_year,1,31).end_of_day
      else
        semester = Time.new(date_year,2,1)..Time.new(date_year,6,30).end_of_day
      end

       i = 0
      loop do
        @lesson = @classroom.lessons.new(lesson_params)
        @lesson.start_time = start
        @lesson.end_time = start + 1.hour
        @lesson.save
        start += 1.week
        i += 1
        break if start > semester.end
      end

    #end

    if @lesson.save

      # Subject name 需保持唯一性，lesson name 編輯時需同步更換同名的 subject
      @subject = @user.subjects.find_or_create_by(name: params[:lesson][:name])
      @subject.classrooms << @classroom unless @subject.classrooms.exists?(@classroom.id)

      flash[:notice] = "行事曆已增添一筆資料"
      redirect_to user_lessons_path
    else
      flash.now[:alert] = "資料未能在行事曆上新增成功"
      render :new
    end
  end

  def edit
  end

  def update
    # @lesson = Lesson.find_by_id(params[:lesson][:id])
    if params[:lesson][:commit_button] == "更新之後的課程"
      # 以下編輯中，待接新增科目
      @lessons = @lesson.classroom.lessons #.find(:all, :conditions => ["starttime > '#{@event.starttime.to_formatted_s(:db)}' "])
      @lesson.update_lessons(@lessons, lesson_params)
    elsif params[:lesson][:commit_button] == "更新整學期的課程"
      # 以下編輯中，待接新增科目
      @lessons = @event.event_series.events.find(:all, :conditions => ["starttime > '#{@event.starttime.to_formatted_s(:db)}' "])
      @lesson.update_events(@events, event_params)
    else # "更新這堂課" 編輯完成
      @lesson.attributes = lesson_params
      @lesson.save
      flash[:notice] = "行事曆已更新一筆資料"
      redirect_to user_lessons_path
    end
  end
  
  def destroy
    # 以下編輯中，待接新增科目
    if params[:delete_all] == '刪除整學期的課程'
      @lesson.event_series.destroy
    # 以下編輯中，待接新增科目
    elsif params[:delete_all] == '刪除之後的課程'
      @lessons = @event.event_series.events.find(:all, :conditions => ["starttime > '#{@event.starttime.to_formatted_s(:db)}' "])
      @lesson.event_series.events.delete(@events)
    # 刪除這堂課 編輯完成
    else
      @lesson.destroy
      flash[:alert] = "行事曆一筆資料已成功刪除"
      redirect_to user_lessons_path
    end
  end

  private
  # 設定使用者
  def set_lesson
    @lesson = Lesson.find_by_id(params[:id])
  end
  
  # 顯示使用者所擁有的課表
  def set_lessons
    # pluck 方法，輸出 array，第一步就用 each do 展開的話，後面就難收拾了
    subject_ids = Subject.where(user_id: @user).pluck(:id)

    # 一個 id 可行，但塞兩個 id 進去 SQL 語法就爆了
    # classroom_ids = Classroom.joins("join classrooms_subjects on classrooms.id = classrooms_subjects.classroom_id").where(["classrooms_subjects.subject_id = ?", subject_ids]).pluck(:id)
    # 適用於 HABTM，外鍵被移掉需要合併 subjects 來撈資料
    classroom_ids = Classroom.joins(:subjects).where(subjects: { id: subject_ids })

    # classroom_id 欄位，輸入 id array，輸出 lessons 的 ActiveRecord，不需要用 id 各別宣告再收集起來。
    @lessons = Lesson.where(classroom_id: classroom_ids, event_type: "lesson")
  end

  def set_subject_of_lesson
    lesson = Lesson.find_by_id(params[:id])
    # 注意：不用路由 params 也可將 id 傳入，但括號內不可使用"實例變數"。此方法可避免巢狀路由過於複雜。
    classroom_id = Classroom.find_by_id(lesson.classroom_id).id
    # SQL 語法，只吃 id 不吃物件
    subjects = Subject.joins("join classrooms_subjects on subjects.id = classrooms_subjects.subject_id").where(["classrooms_subjects.classroom_id = ?", classroom_id])
    # 這個資料撈法要在 @subject name 唯一性，且 @subject 及其下的 @lessons 的名稱需同步 CRUD 才行！
    # 若 .first 沒加，撈到的是 relation 無法使用關聯方法
    @subject = subjects.where(name: lesson.name).first

    
    @classroom = Classroom.find(lesson.classroom_id)
  end

  def set_user
    # 使用者可以經路由看到別人的課表，分享課表功能
    @user = User.find_by_id(params[:user_id])
  end

  def set_author
    @user = current_user
  end

  def lesson_params
    params.require(:lesson).permit(:name, :start_time,'start_time(1i)', 'start_time(2i)', 'start_time(3i)', 'start_time(4i)', 'start_time(5i)', 'end_time(1i)', 'end_time(2i)', 'end_time(3i)', 'end_time(4i)', 'end_time(5i)', :period, :frequency, :commit_button, :event_type, :grade, :room,:student)
  end

end

app/views/lessons/_edit_form.html.erb
<%= form_for [@user, @lesson] do |f| %>
<%# 不需指定 action，名稱套用慣例 %>

  <div class="form-group">
    <%=f.label :name %>
    <br/>
    <%=f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%=f.label :start_time, 'Start Time' %>
    <br/>
    <%=f.datetime_select :start_time %>
  </div> 

  <div class="actions">
    <%# if @classroom -%>
      <%= f.submit "更新這堂課", class: "btn btn-secondary" %>
      <%= f.submit "更新之後的課程", class: "btn btn-info" %>
      <%= f.submit "更新整學期的課程", class: "btn btn-danger" %>
    <%# else -%>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <%# end -%>
  </div>

<%end %>

app/views/lessons/_form.html.erb
<%= form_for [@user, @lesson], url: {action: "create"}  do |f| %>

  <div class="form-group col-8 font-24">
    <%= f.label :name, "課程科目" %>
    <br/>
    <%= f.select :name, Subject::SUBJECT,{}, class: "form-control" %>
  </div>

  <div class="form-row col-8">
    <div class="col font-24">
      <%= f.label :grade, "年級" %>
      <% grade_array = Classroom::GRADE.map { |grade| grade + "年"} %>
      <%= f.select :grade, grade_array,{}, class: "form-control" %>
    </div>
    <div class="col font-24">
      <%= f.label :room, "班級" %>
      <%= f.text_field :room, class: "form-control", placeholder: "ex. 1班" %>
    </div> 
    <div class="col font-24">
      <%= f.label :student, "學生人數" %>
      <%= f.text_field :student, class: "form-control" %>
    </div>
  </div>

  <div class="form-group col-8 font-20 mt-4">
    <%= f.label :start_time, '課堂開始時間（一節）' %>
    <span>*如需新增多節課堂，請點擊首頁 <i class="fa fa-calendar-plus-o font-20" aria-hidden="true" style="color: #527a7a;"></i> 再次新增</span>
    <br/>
    <%= f.datetime_select :start_time, discard_minute: true, start_hour: 8, end_hour: 18, ampm: true, default: Date.today.beginning_of_day + 8.hour %>
  </div>

  <div class="actions col-8 mt-4">
    <%= f.submit "新增", class: "btn btn-outline-info" %>
    <%= link_to "取消",user_lessons_path(@user) ,class: "btn btn-outline-dark" %>
  </div>

<%end %>

app/views/lessons/_month_calendar.html.erb
<%= month_calendar events: lessons do |date, lessons| %>
  <%= link_to url_for(request.parameters.merge(start_date: date)) do %>
    <%= date.day %>
  <% end %>
<% end %>

app/views/lessons/_todo_list.html.erb
<div class="to_do_body mt-4"> 
  <%# 客制化各項需以逗號分開 %>
  <!--待辦清單-->
  <div id="todo_content">
  <%= calendar partial: 'simple_calendar/to_do_list_v2', number_of_days: 1, events: todos do |date, todos| %>
    <% 8.upto(18).each do |hour| %>
      <div class="day_time">
        <span class="day_time_hour"><%= Time.parse("#{hour}:00").strftime("%l %P") %></span>
        <span id="hour-<%= hour %>">
          <% todos.each do |todo| %> 
            <%- if todo.start_time.hour.between?(hour, hour + 0.9) %>
              <%# ajax %>
              <%= render partial:'events/event',locals:{todo: todo} %>
              <%# 一般版 %>
              <%#= link_to edit_user_event_path(@user, todo) do %>
                <%#= todo.title %>
              <%# end %>
            <% end -%>         
          <% end %>
        </span>
      </div>
    <% end %>
  <% end %>   
  </div>
</div> 
  
<%# ajax 版 以下為新增代辦事項的form  #############################################  %>
<%= form_for [@user, @todo] do |f| %>
  <div class="modal fade" id="todopost" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%# create todo modal header %>
        <div class="modal-header">
          <h5 class="modal-title" id="myModalLabel">待辦事項</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
         <div class="modal-body">
          <%# modal-body 開始 %>
          <div class="form-group">
            <%= f.label '待辦事項' %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
           <div class="form-group">
            <%= f.label '開始時間' %>
            <%= f.datetime_select :start_time, start_year: Date.today.year, end_year: Date.today.year+1, start_hour: 8, end_hour: 18, ampm: true, discard_minute: true, default: Date.today.beginning_of_day + 8.hour %>
          </div>
           <%# <div class="form-group"> 暫時關閉 end_time 選項 %>
            <%#= f.label '結束時間' %>
            <%#= f.datetime_select :end_time, start_year: Date.today.year, end_year: Date.today.year+1, start_hour: 8, end_hour: 18, ampm: true, discard_minute: true, default: Date.today.beginning_of_day + 9.hour %>
          <%# </div> %>
           <%# modal-body 結束  %>
        </div>  
         <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">取消</button>
          <%= f.submit '新增' ,class:"btn btn-primary"%>
        </div>
      <%# modal content 結束  %>
      </div>
    </div>
  </div>
<% end %>

app/views/lessons/_week_calendar.html.erb
<div class="time_table">
  <%= week_calendar events: lessons do |date, lessons| %>
    <% 8.upto(18).each do |hour| %>
      <div id="hour-<%= hour %>" class="day_time text-center">
        <% lessons.each do |lesson| %>
          <div class="lesson-content">
            <%- if lesson.start_time.hour.between?(hour, hour + 0.9) %>
              <%= link_to user_lesson_path(@user, lesson) do %>
                <%#= lesson.topic.name %>
                <div><%= lesson.name %></div>
                <div><%= lesson.grade %> <%= lesson.room %> </div>
              <% end %>
            <% end -%>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<div class="row">
  <%= render 'shared/msg' %>

  <div class="col-12">
    <h1>編輯課程</h1>
    <%= render 'edit_form' %>
  </div>
  <br/>

  <%# buttons %>
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to '編輯', user_lesson_path(@user, @lesson), class: "nav-link bg-light" %>
    </li>
    <li class="nav-item">
      <%= link_to '刪除', user_lesson_path(@user, @lesson), method: :delete, data: { confirm: '你確定要刪除嗎?' }, class: "nav-link bg-light" %>
    </li>
    <li class="nav-item">
      <%= link_to '返回', user_lessons_path, class: "nav-link bg-light" %>
    </li>
  </ul>

</div>

app/views/lessons/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12" style="padding-left:60px;padding-right: 40px;">
      <div>
        <h1 class="inline-block">本週教學行程</h1>
        <%#= link_to 'Listing lessons', list_user_lessons_path(@user) %>
        <% if @user == current_user %>
          <i class="fa fa-caret-right grid" aria-hidden="true"></i> 
          <%= link_to '以列表檢視班級', user_classrooms_path(@user),style:"font-size:22px;"  %>
        <% end %>

        <h3 class="inline-block pull-right">今天日期：
          <span class="letter-sp-2"><%= Time.now.strftime("%Y/%m/%d") %></span>
        </h3>
      </div>
      <hr>
    </div> 


    <div id="lessons_calendar" class="col-8" style="margin-left:60px;margin-top: 20px;">
      <div class="index-right-container">
        <div class="row">
          <div class="col-12 m-auto">
            <span id="today_link" class="pull-left">
              <%= link_to '今天', user_lessons_path(@user), class: "btn btn-outline-dark btn-sm",style:"padding:5px 20px;font-size:15px;" %>
            </span>
            <div id="events_calendar">
              <%= render partial: "week_calendar", locals: {lessons: @lessons} %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="lessons_calendar_2" class="col-3 ml-4" >
      <div class="index-left-container">
        <div class="row">
          <div class="col-12">
            <%# 右上月曆 %>
            <div id="month_calendar">
              <%= render partial: "month_calendar", locals: {lessons: @lessons} %>
            </div>
            <%# ToDo List V2 %>
            <% if @user == current_user %>
              <div id="todo_list">
                <%= render partial: "todo_list", locals: {todos: @todos} %>
              </div>
            <% end %>
          </div>
        </div>       
      </div>
    </div>
  </div>
</div>

app/views/lessons/index.js.erb
$("#events_calendar").html("<%= escape_javascript render(partial: "week_calendar", locals: {lessons: @lessons}) %>");
$("#month_calendar").html("<%= escape_javascript render(partial: "month_calendar", locals: {lessons: @lessons}) %>");
$("#todo_list").html("<%= escape_javascript render(partial: "todo_list", locals: {todos: @todos}) %>");

app/views/lessons/list.html.erb
<div class="row">
  <div class="col-12">
    <h1>使用者課程列表</h1>
    <hr>
    <%= link_to "<< 返回課表", user_lessons_path(@user) %>
    <br><br>
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>科目</th>
          <th>班級</th>
          <th>課程開始時間</th>
          <th>課程結束時間</th>
          <th colspan="3">#</th>
        </tr>
      </thead>

      <tbody>
        <% @lessons.each do |lesson| %>
          <tr>
            <td><%= lesson.name %></td>
            <td><%= lesson.grade %> <%= lesson.room %></td>
            <td><%= lesson.start_time.strftime("%Y-%m-%d") %></td>
            <td><%= lesson.end_time.strftime("%Y-%m-%d") %></td>
            <td><%= link_to '瀏覽', user_lesson_path(@user, lesson) %></td>
            <td><%= link_to '編輯', edit_user_lesson_path(@user, lesson) %></td>
            <td><%= link_to '刪除', user_lesson_path(@user, lesson), method: :delete, data: { confirm: '確定要刪除嗎?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render 'shared/msg' %>

    <div class="col-12">
      <h1 class="inline pl-4">新增各學期課堂</h1>
      <i class="fa fa-caret-right grid" aria-hidden="true"></i> 
      <%= link_to '回到課表首頁', user_lessons_path(@user), class: "font-22" %>
      <hr>
      <div class="lesson-form-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
<!--
<div class="row">
  <div class="col-12">
    <%#= render 'shared/msg' %>

    <div class="form-group">
      <h1><%#= @lesson.name %></h1>
    </div>

    <div class="form-group">
      <h4><%= @lesson.grade %> <%= @lesson.room %></h4>
    </div>

    <p>
      <strong>Start time:</strong>
      <%= @lesson.start_time %>
    </p>

    
    <%# buttons %>
    <div>
      <%#= link_to '編輯', edit_user_lesson_path(@user, @lesson), class: "btn btn-primary" %>
      <%#= link_to '刪除', user_lesson_path(@user, @lesson), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <%#= link_to '返回', user_lessons_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>
<-->
<div class="container"> 
  <div class="">
    <div class="float-left">
      <h1>管理教學計劃與課程進度</h1>
      <h4>課程： <%= @subject.name %></h4>  
      <h4>班級： <%= @lesson.classroom.name %>（<%= @lesson.classroom.student %> 人）</h4>
      <% if @user == current_user %>
        <%= link_to '我的課表', user_lessons_path(@user),style:"font-size:18px;"  %> | <%= link_to '檢視班級列表', user_classrooms_path(@user),style:"font-size:18px;"  %>
      <% end %>
    </div>
    <div class="float-right">
      <%#= link_to '課程設定', edit_user_lesson_path(@user, @lesson), class: "btn btn-outline-dark" %>
    </div>
    <h3 class="inline-block pull-right">今天日期：
      <span class="letter-sp-2"><%= Time.now.strftime("%Y/%m/%d") %></span>
    </h3>
    <div class="clearfix"></div>

  </div>
  <hr>
  
  <%# 以下為新增的科目內容，只有 lesson 才顯示以下內容 %>
  <% if @lesson.event_type == "lesson" %>
    <% if @user == current_user %>
      <span class="text-center">
        <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#mynewpost">
          <h4><%= fa_icon 'plus' %>&nbsp;&nbsp;新增教學計劃</h4>
        </button>  
      </span>
    <% end %>

    <div id="container_posts">
      <% if @classroom.topics.count < 1 %>
        <h4 class="mt-4">新增教學單元請點擊上方的「新增教學計畫」</h5>
        <%#= @topics.each do |topic| %>
          <%#= render partial:'topics/topic',locals: {topic: topic } %>
        <%# end %>
      <% else %>  
        <% @topics.each do |topic|%>  
          <%= render partial:'topics/topic',locals: {topic: topic } %>
        <% end %>
      <% end %>
        
    </div>
       
  <% end %>


  <%= form_for [@user,@classroom,@topic] do |f| %>
    <div class="modal fade" id="mynewpost" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="myModalLabel">設定時間／教學主題</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="modal-body">
              <%# modal-body %>
                <!--輸入主題日期開始-->
                <div class="field">
                  <%= f.label "開始日期" %>
                  <%= f.date_select :start_time, class: 'form-control post_theme' %>
                </div>
              
                <!--輸入主題日期結束-->
                
                <div class="field">
                  <%= f.label "結束日期" %>
                  <%= f.date_select :end_time, class: 'form-control post_theme' %>
                </div>

                <!--輸入教學主題-->
                
                <div class="field">
                  <%= f.label "教學單元主題" %>
                  <%= f.text_field :name, class: 'form-control post_theme', placeholder: "輸入教學主題" %>
                </div>
              
              <%# modal-body  %>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">close</button>
              <%= submit_tag "create",class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>