config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#show"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :photos, only: [:index, :create, :show, :update, :destroy]
    end
  end

  resources :subject_tags

  resources :users do

    member do
      get :viewfile
    end

    resources :plans do
      resources :teachingfiles do
        resources :attachments, only: :destroy do
        end
      end
    end

    resources :materials do
      resources :teachingfiles do
        resources :attachments, only: :destroy do
        end
      end
    end

    resources :classrooms do
      resources :topics do
        resources :teachingfiles do
          member do
            post :addfile
            post :removefile
          end
        end
        
        resources :aims
      end
    end

    resources :subjects

    resources :events

    resources :lessons do
      collection do
        get :list
      end
    end
  end

end

app/models/plan.rb
#  == Schema Information
#
#  Table names : plans
#
#  id               :integer     not null, primary key
#  plan_folder_name :string
#  created_at       :datetime    not null
#  updated_at       :datetime    not null
#
#  subject_id       :integer

class Plan < ApplicationRecord
  #before_action :authenticate_user!
  
  #belongs_to :subject
  validates_presence_of :plan_folder_name
  belongs_to :subject_tag
  belongs_to :user
  has_many :teachingfiles, dependent: :destroy
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :find_user, only: [:index, :show]
  before_action :set_user, only: [:create, :update, :destroy]
  before_action :find_plan, only: [:update, :destroy]
  before_action :set_plan, only: [:edit, :show, :update, :destroy]

  def index
    @plans = @user.plans.order(created_at: :desc)
    # 瀏覽別人的頁面要把"新增按鈕"蓋掉
    @plan = current_user.plans.new
    subject_tag_ids = @user.plans.pluck(:subject_tag_id)
    @subject_tags = SubjectTag.where(id: subject_tag_ids)
  end

  def show
    if params[:user_id]
      @plan = @user.plans.find(params[:id])
      if params[:plan_id]
        @teachingfile = @plan.teachingfiles.find(params[:id])
      else
        @teachingfile = Teachingfile.new
      end
    end
  end

  def create
    @plan = @user.plans.new(plan_params)
    if @plan.save!
      flash[:notice] = "成功新增資料夾【#{@plan.plan_folder_name}】"
      redirect_to user_plans_path(current_user)# @plans 轉 index 不需要加這個，轉址後網址掛一包 active record，危險
    else
      flash[:alert] = "請確定選擇科目及填上主題／單元名稱！"
      render :new
    end 
  end

  def update
    if @plan.update(plan_params)
      flash[:notice] = "更新教案資料夾設定"
      redirect_to user_plans_path
    else
      flash[:alert] = "更新失敗，請確定填上主題／單元名稱！"
      redirect_to user_plan_path(@user, @material)
    end
  end

  def destroy
    @plan.destroy
    redirect_to user_plans_path
    flash[:alert] = "#{@plan.plan_folder_name}資料夾已刪除"
  end

  private

  def find_user
    @user = User.find_by_id(params[:user_id])
  end

  def set_user
    @user = current_user
  end

  def find_plan
    @plan = @user.plans.find(params[:id])
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:user_id,:plan_folder_name,:subject_tag_id)
  end

end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/index.html.erb
<div class="container">
  <h1>
    教案資料夾
    <% if @user == current_user %>
      <div id="new_event_button" class="inline">
        <a href="" data-toggle="modal" data-target="#exampleModal">
          <%= fa_icon "plus-circle 3x", style: 'color: #83c867' %>
        </a>
      </div>
    <% end %>
  </h1>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">新增資料夾</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_for [@user,@plan] do |f| %>
            <div class="form-group">
            <%= f.label :subject_tag_id, "科目" %>
            <%= f.collection_select :subject_tag_id , SubjectTag.all, :id, :name, {prompt: true}, {class: "form-control"}  %>
            </div>
            <div class="form-group">
            <%= f.label :plan_folder_name, "教學主題／單元" %>
            <%= f.text_field :plan_folder_name ,class: "form-control"%>
            </div>

            <div class="form-group">
              <% if @plan.plan_folder_name.present? %>
                <%= f.submit '修改', class: 'btn btn-outline-info' %>
                <%= link_to '取消', user_plans_path(@user), class: 'btn btn-outline-danger' %>
              <% else %>
                <%= f.submit '新增', class: 'btn btn-info' %>
              <% end %> 
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <br>
  <div class="row justify-content-center">
    <div class="col-md-10 table-card">
      <% if @plans.count == 0 %>
        <h4>你還沒有任何教案資料！</h4>
      <% else %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">科目</th>
              <th scope="col">主題／單元</th>
              <!--<th scope="col">上次修改日期</th>-->
            </tr>
          </thead>
          <tbody>
            <% @subject_tags.each do |subject| %>
              <%# if subject.plans.present? %> <%# 舊設定會包含別的使用者一起判斷，所以在別有人有 plan 自己沒有時，就會出現格內無 plan 的狀況。而且還會把別人的 plan 傳進來，點擊結結會出錯，plan_id 和 params 給入的 user_id 湊不起來 %>
              <tr>
                <th><%= subject.name %></th>
                <td>
                  <% @plans.each do |plan| %>
                    <% if plan.subject_tag.name == subject.name %>
                      <%= link_to user_plan_path(@user,plan) do %>  
                        <%= fa_icon 'folder', style: 'color:grey;' %>&nbsp;&nbsp;
                        <span><%= plan.plan_folder_name %></span> 
                      <% end %><br> 
                    <% end %>
                  <% end %>
                </td>
                 <%#= plan.updated_at.strftime("%Y/%m/%d") %><%# @plans block 包到這邊會跑版 %>
               
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>

  </div>

</div>

app/views/plans/show.html.erb
<div class="container">
  <div class="">
    <div class="float-left">
      <h1><%= @plan.subject_tag.name %>：<%= @plan.plan_folder_name %></h1>
      <%= link_to user_plans_path(@user) do %>
        <%= fa_icon 'caret-left' %> &nbsp;
        <span class="font-22">返回教案總覽</span>
      <% end %>
    </div>
    <% if @user == current_user %>
      <div class="float-right">
        <button type="button" class="btn btn-outline-dark btn-md" data-toggle="modal" data-target="#exampleModal">
          資料夾設定
        </button>
        <%= link_to '刪除資料夾', user_plan_path(@plan.user,@plan), class: 'btn btn-danger btn-md', style: "color: #fff;", method: :delete, data: {confirm: "資料夾裡的檔案也會一併刪除，你確定嗎？"} %>
      </div>
    <% end %>

    <div class="clearfix"></div>  
    <hr>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">編輯資料夾</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= form_for [@user,@plan] do |f| %>
              <div class="form-group">
              <%= f.label :subject_tag_id, "科目" %>
              <%= f.collection_select :subject_tag_id , SubjectTag.all, :id, :name, {prompt: true}, {class: "form-control"} %>
              </div> 

              <div class="form-group">
              <%= f.label :plan_folder_name, "教學主題／單元" %>
              <%= f.text_field :plan_folder_name ,class: "form-control"%>
              </div>

              <div class="form-group pull-right">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                <%= f.submit '變更設定', class: 'btn btn-info' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if @user == current_user %>
    <div class="row">
      <div class="col-md-3">
        <%= form_for [@user,@plan,@teachingfile], html:{multipart:true} do |f| %>
          <div class="form-group">
            <%= f.label :name, '檔案名稱' %>
            <%= f.text_field :name, class: 'form-control', placeholder: "自訂" %>
          </div>

          <div class="form-group">
            <%= f.label :attachments,'上傳附件' %>
            <%= f.file_field :attachments, multiple: true %>
          </div><br>

          <%= f.submit "上傳", class: "btn btn-outline-info" %>

        <% end %>
      </div>
      <div class="col-md-9">
        <div class="table-card">
          <br>
          <h3 class="text-center">上傳檔案列表</h3>
          <br>
          <table class="table table-hover">
            <% @plan.teachingfiles.each do |teachingfile| %>
            <tr>
              <td style="padding-right:20px;"><h5><%= teachingfile.name %><h5></td>
              <td style="padding-right:20px;">
                <% teachingfile.attachments.each_with_index do |file, index| %>
                <div>
                  <%= link_to file.url do %>
                    <%= fa_icon 'download 1x', class: 'theme-font' %>&nbsp;&nbsp;
                    <%= file.file.filename %>
                  <% end %>
                  <%= link_to user_plan_teachingfile_attachment_path(@user, @plan, teachingfile, index), :method => :delete, data: { confirm: "要刪除《#{file.file.filename}》檔案嗎？" } do %>
                    &nbsp;&nbsp;<%= fa_icon 'trash', style: 'color: red;'%>
                  <% end %>
                </div>
                <% end %>
              </td>
              <td style="margin-right:20px;">
                <div class="float-right">
                  <%= link_to '重新上傳',edit_user_plan_teachingfile_path(@user, @plan,teachingfile) %> | <%= link_to '全部刪除', user_plan_teachingfile_path(@user, @plan,teachingfile), method: :delete, data: { confirm: "確定要刪除這個檔案嗎？"}, style: "color: red;" %>
                </div>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="table-card">
          <br>
          <h3 class="text-center">上傳檔案列表</h3>
          <br>
          <table class="table table-hover">
            <% @plan.teachingfiles.each do |teachingfile| %>
            <tr>
              <td style="padding-right:20px;"><h5><%= teachingfile.name %><h5></td>
              <td style="padding-right:20px;">
                <% teachingfile.attachments.each_with_index do |file, index| %>
                <div>
                  <%= link_to file.url do %>
                    <%= fa_icon 'download 1x', class: 'theme-font' %>&nbsp;&nbsp;
                    <%= file.file.filename %>
                  <% end %>
                  <% if @user == current_user %>
                    <%= link_to user_plan_teachingfile_attachment_path(@user, @plan, teachingfile, index), :method => :delete, data: { confirm: "要刪除《#{file.file.filename}》檔案嗎？" } do %>
                      &nbsp;&nbsp;<%= fa_icon 'trash', style: 'color: red;'%>
                    <% end %>
                  <% end %>
                </div>
                <% end %>
              </td>
              <% if @user == current_user %>
                <td style="margin-right:20px;">
                  <div class="float-right">
                    <%= link_to '重新上傳',edit_user_plan_teachingfile_path(@user, @plan,teachingfile) %> | <%= link_to '全部刪除', user_plan_teachingfile_path(@user, @plan,teachingfile), method: :delete, data: { confirm: "確定要刪除這個檔案嗎？"}, style: "color: red;" %>
                  </div>
                </td>
              <% end %>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>